/**
 * @fileoverview gRPC-Web generated client stub for com.naga.grpcweb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.30.2
// source: stock.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.com = {};
proto.com.naga = {};
proto.com.naga.grpcweb = require('./stock_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.naga.grpcweb.StockServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.naga.grpcweb.StockServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.naga.grpcweb.StockRequest,
 *   !proto.com.naga.grpcweb.StockUpdate>}
 */
const methodDescriptor_StockService_GetStockUpdates = new grpc.web.MethodDescriptor(
  '/com.naga.grpcweb.StockService/GetStockUpdates',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.com.naga.grpcweb.StockRequest,
  proto.com.naga.grpcweb.StockUpdate,
  /**
   * @param {!proto.com.naga.grpcweb.StockRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.naga.grpcweb.StockUpdate.deserializeBinary
);


/**
 * @param {!proto.com.naga.grpcweb.StockRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.com.naga.grpcweb.StockUpdate>}
 *     The XHR Node Readable Stream
 */
proto.com.naga.grpcweb.StockServiceClient.prototype.getStockUpdates =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/com.naga.grpcweb.StockService/GetStockUpdates',
      request,
      metadata || {},
      methodDescriptor_StockService_GetStockUpdates);
};


/**
 * @param {!proto.com.naga.grpcweb.StockRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.com.naga.grpcweb.StockUpdate>}
 *     The XHR Node Readable Stream
 */
proto.com.naga.grpcweb.StockServicePromiseClient.prototype.getStockUpdates =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/com.naga.grpcweb.StockService/GetStockUpdates',
      request,
      metadata || {},
      methodDescriptor_StockService_GetStockUpdates);
};


module.exports = proto.com.naga.grpcweb;

