spring.main.web-application-type=reactive
spring.main.allow-bean-definition-overriding=true
grpc.server.security.enabled=false

# Disable gRPC tracing auto-configuration
grpc.client.GLOBAL.tracing.enabled=false
grpc.server.tracing.enabled=false

# Enable gRPC Web support
grpc.server.cloud-discovery.enabled=false
grpc.server.port=9090
grpc.server.http-port=8080
# Enable gRPC-Web - this is crucial
grpc.server.reflection.enabled=true

grpc.server.in-process-name=grpc-server
# Enable gRPC-Web
grpc.server.grpc-web.enabled=true
grpc.server.grpc-web.cors-mappings[0].path-pattern=/**
grpc.server.grpc-web.cors-mappings[0].allowed-origins=*
grpc.server.grpc-web.cors-mappings[0].allowed-methods=GET,POST
grpc.server.grpc-web.cors-mappings[0].allowed-headers=*


logging.level.io.grpc.netty=DEBUG
logging.level.reactor.netty=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG


logging.level.org.springframework.web=DEBUG
logging.level.com.naga=TRACE
logging.level.root=INFO

